server:
  port: 8080

app:
  jwtSecret: declaracionRentaSecretKey
  jwtExpirationMs: 86400000
  uvt:
    4500: 160232000
    1400: 49850000

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none  #update
  datasource:
    url: jdbc:mysql://db-mysql-nyc1-renta-do-user-9756002-0.b.db.ondigitalocean.com:25060/renta
    username: doadmin
    password: zuJc9ymf1YUFRpgq
    platform:

